version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-lint:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn install
            - run: yarn lint
            - run: yarn build
workflows:
    build-and-lint:
      jobs:
        - build-and-lint